name: pybullet37
channels:
  - conda-forge
  - defaults
dependencies:
  - bullet-cpp=3.21=h4abc668_3
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - libblas=3.11.0=1_he492b99_openblas
  - libcblas=3.11.0=1_h9b27e0a_openblas
  - libcxx=21.1.6=h3d58e20_0
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=15.2.0=h306097a_1
  - libgfortran5=15.2.0=h336fb69_1
  - liblapack=3.11.0=1_h859234e_openblas
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libxcb=1.17.0=hf1f96e2_0
  - llvm-openmp=21.1.6=h472b3d1_0
  - ncurses=6.5=h923df54_0
  - numpy=1.21.6=py37h345d48f_0
  - openssl=1.1.1w=hca72f7f_0
  - pip=22.3.1=py37hecd8cb5_0
  - pthread-stubs=0.4=h00291cd_1002
  - pybullet=3.21=py37h4abc668_3
  - python=3.7.16=h218abb5_0
  - python_abi=3.7=2_cp37m
  - readline=8.3=h49f2429_0
  - setuptools=65.6.3=py37hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - wheel=0.38.4=py37hecd8cb5_0
  - xorg-libx11=1.8.12=h217831a_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - xorg-libxext=1.3.6=h00291cd_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - appnope==0.1.4
      - backcall==0.2.0
      - decorator==5.1.1
      - ipython==7.34.0
      - jedi==0.19.2
      - matplotlib-inline==0.1.6
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - prompt-toolkit==3.0.48
      - ptyprocess==0.7.0
      - pygments==2.17.2
      - traitlets==5.9.0
      - wcwidth==0.2.14
prefix: /opt/anaconda3/envs/pybullet37
